language: go
go:
 - 1.5
 - 1.6
sudo: required
dist: trusty
before_install:
 - ./couchdb2.0-install.sh
before_script:
 - curl -X PUT http://127.0.0.1:5984/_config/admins/adminuser -d '"password"'
script:
 - go get github.com/twinj/uuid
 - go test -v ./...
